const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('annotate', {
  state: () => ipcRenderer.invoke('state'),
  target: id => ipcRenderer.invoke('target', id),
  desktopConfig: () => ipcRenderer.invoke('desktop-config'),
  desktopMark: (points, complete = false) => ipcRenderer.invoke('desktop-mark', points, complete),
  onDesktopProgress: callback => ipcRenderer.on('desktop-progress', (_event, mark) => callback(mark)),
  capture: options => ipcRenderer.invoke('capture', options),
  select: id => ipcRenderer.invoke('select', id),
  sources: () => ipcRenderer.invoke('sources'),
  chooseSource: id => ipcRenderer.invoke('choose-source', id),
  cropApp: points => ipcRenderer.invoke('crop-app', points),
  mark: (kind, points) => ipcRenderer.invoke('mark', kind, points),
  frozen: () => ipcRenderer.invoke('frozen'),
  cancel: () => ipcRenderer.invoke('cancel'),
  add: item => ipcRenderer.invoke('add', item),
  remove: id => ipcRenderer.invoke('remove', id),
  comment: (id, comment) => ipcRenderer.invoke('comment', id, comment),
  clear: () => ipcRenderer.invoke('clear'),
  send: targetId => ipcRenderer.invoke('send', targetId),
  quit: () => ipcRenderer.invoke('quit'),
  portalReady: () => ipcRenderer.invoke('portal-ready'),
  portalResult: result => ipcRenderer.invoke('portal-result', result),
  onChange: callback => ipcRenderer.on('state-changed', () => callback()),
  onNotice: callback => ipcRenderer.on('notice', (_event, message) => callback(message)),
});
